### ISSUE TITLE
add_docker - "bash docker: command not found"

### ISSUE THREAD

**Issue by stepanic** [codeship/codeship-tool-examples#17]
This example was working since 18th of November 2015th
https://github.com/codeship/codeship-tool-examples/blob/master/14.add_docker/codeship-services.yml

It seems that maintainer at repo at Docker Hub has made some changes
https://hub.docker.com/r/jpetazzo/dind/~/dockerfile/

Can you please put stable image for `add_docker` at official codeship Docker Hub account because we use add_docker in production 

Now all our builds failed at project https://codeship.com/projects/82028

**Comment by rheinwein** [comment]
Hi @stepanic, this issue is related to the base image used for the add_docker feature. We've submitted a PR to fix the problem. Please follow https://github.com/jpetazzo/dind/issues/96 and http://codeshipstatus.com/incidents/3sxlsmqtxbvd for updates.
