### ISSUE TITLE
error loading encrypted environment file 

### ISSUE THREAD

**Issue by jjmonsalveg** [codeship/codeship-tool-examples#31]
Hello everybody, i want run example  11.encrypted-aes (jet steps) but  i get this error :

`{StepFinished=step_name:"./check_for_foo.sh" type:STEP_FINISHED_TYPE_ERROR}
error loading encrypted environment file environment.encrypted.ci: environment contains non-utf8 characters: `

somebody Can help me please,my docker engine Version:  1.12.3 and my jet  Version: 1.14.5

**Comment by bfosberry** [comment]
Hey thanks for reporting this, I opened a PR to switch the example services file over to the correct one, you can patch locally by switching the file in the services file as shown in the attached PR. 

The issue is that the .ci file was encrypted with the project AES key, not the examples one

**Comment by jjmonsalveg** [comment]
oh! thanks @bfosberry
